//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyLogic.Mamdani {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuzzyLogic.Mamdani.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на problemConditions.
        /// </summary>
        internal static string ProblemConditionsNodeName {
            get {
                return ResourceManager.GetString("ProblemConditionsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на input.
        /// </summary>
        internal static string RuleNodeInputSectionName {
            get {
                return ResourceManager.GetString("RuleNodeInputSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rule.
        /// </summary>
        internal static string RuleNodeName {
            get {
                return ResourceManager.GetString("RuleNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на output.
        /// </summary>
        internal static string RuleNodeOutputSectionName {
            get {
                return ResourceManager.GetString("RuleNodeOutputSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rules.
        /// </summary>
        internal static string RulesNodeName {
            get {
                return ResourceManager.GetString("RulesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на variable.
        /// </summary>
        internal static string RuleVariableNodeName {
            get {
                return ResourceManager.GetString("RuleVariableNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на name.
        /// </summary>
        internal static string RuleVariableNodeNameAttribute {
            get {
                return ResourceManager.GetString("RuleVariableNodeNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на value.
        /// </summary>
        internal static string RuleVariableNodeValueAttribute {
            get {
                return ResourceManager.GetString("RuleVariableNodeValueAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a.
        /// </summary>
        internal static string TermAPointAttributeName {
            get {
                return ResourceManager.GetString("TermAPointAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b.
        /// </summary>
        internal static string TermBPointAttributeName {
            get {
                return ResourceManager.GetString("TermBPointAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c.
        /// </summary>
        internal static string TermCPointAttributeName {
            get {
                return ResourceManager.GetString("TermCPointAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d.
        /// </summary>
        internal static string TermDPointAttributeName {
            get {
                return ResourceManager.GetString("TermDPointAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на term.
        /// </summary>
        internal static string TermNodeName {
            get {
                return ResourceManager.GetString("TermNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на name.
        /// </summary>
        internal static string TermNodeNameAttribute {
            get {
                return ResourceManager.GetString("TermNodeNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на isResult.
        /// </summary>
        internal static string VariableNodeIsResultAttribute {
            get {
                return ResourceManager.GetString("VariableNodeIsResultAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lingName.
        /// </summary>
        internal static string VariableNodeLingNameAtttribute {
            get {
                return ResourceManager.GetString("VariableNodeLingNameAtttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на variable.
        /// </summary>
        internal static string VariableNodeName {
            get {
                return ResourceManager.GetString("VariableNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на name.
        /// </summary>
        internal static string VariableNodeNameAttribute {
            get {
                return ResourceManager.GetString("VariableNodeNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на variables.
        /// </summary>
        internal static string VariablesNodeName {
            get {
                return ResourceManager.GetString("VariablesNodeName", resourceCulture);
            }
        }
    }
}
